<?php
require_once '/var/www/src/helpers.php';
require_once '/var/www/src/ai.php';
$allowedOrigin = getenv('CORS_ORIGIN') ?: 'http://localhost:8090';
if (isset($_SERVER['HTTP_ORIGIN']) && $_SERVER['HTTP_ORIGIN'] === $allowedOrigin) {
  header('Access-Control-Allow-Origin: '.$allowedOrigin);
  header('Vary: Origin');
}
header('Access-Control-Allow-Headers: Content-Type, Authorization'); header('Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS');
if($_SERVER['REQUEST_METHOD']==='OPTIONS') exit;
$m=$_SERVER['REQUEST_METHOD']; $p=path_parts(); $r=$p[0]??''; $id=isset($p[1])?(int)$p[1]:null;
try {
 if($r==='health') json_out(['status'=>'ok','database'=>db()->query('SELECT 1')->fetchColumn()==1]);
 if($r==='login'&&$m==='POST'){ $d=body(); need($d,['email','password']); $s=db()->prepare('SELECT * FROM users WHERE email=? AND active=1'); $s->execute([$d['email']]); $u=$s->fetch(); if(!$u||!password_verify($d['password'],$u['password_hash'])) json_out(['message'=>'Email hoặc mật khẩu không đúng'],401); $token=bin2hex(random_bytes(32)); db()->prepare('INSERT INTO api_tokens(user_id,token_hash,expires_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 8 HOUR))')->execute([$u['id'],hash('sha256',$token)]); unset($u['password_hash']); json_out(['token'=>$token,'user'=>$u]); }
 if($r==='logout'&&$m==='POST'){ current_user(); db()->prepare('DELETE FROM api_tokens WHERE token_hash=?')->execute([hash('sha256',bearer())]); json_out(['message'=>'Đã đăng xuất']); }
 if($r==='me'&&$m==='GET') json_out(current_user());
 if($r==='stats'&&$m==='GET'){ current_user(); $q=db(); json_out(['books'=>(int)$q->query('SELECT COALESCE(SUM(quantity),0) FROM books')->fetchColumn(),'available'=>(int)$q->query('SELECT COALESCE(SUM(available),0) FROM books')->fetchColumn(),'readers'=>(int)$q->query("SELECT COUNT(*) FROM readers WHERE status='active'")->fetchColumn(),'borrowed'=>(int)$q->query("SELECT COUNT(*) FROM loans WHERE status IN ('open','overdue')")->fetchColumn(),'overdue'=>(int)$q->query("SELECT COUNT(*) FROM loans WHERE status='overdue'")->fetchColumn()]); }
 if($r==='books'){
   current_user(); if($m==='GET'){ $q=trim($_GET['q']??'');$status=$_GET['status']??'';$sql='SELECT * FROM books WHERE 1';$a=[];if($q!==''){$sql.=' AND (title LIKE ? OR author LIKE ? OR category LIKE ?)';$v="%$q%";$a=[$v,$v,$v];}if($status==='available')$sql.=' AND available>0';if($status==='borrowed')$sql.=' AND available<quantity';$sort=in_array($_GET['sort']??'',['title','author','year','available'])?$_GET['sort']:'id';$sql.=" ORDER BY $sort"; $s=db()->prepare($sql);$s->execute($a);json_out($s->fetchAll()); }
   require_role('librarian'); $d=body(); if($m==='POST'){need($d,['title','author','category','year','quantity']); if((int)$d['quantity']<1)json_out(['message'=>'Số lượng phải lớn hơn 0'],422); db()->prepare('INSERT INTO books(title,author,category,year,quantity,available,description) VALUES(?,?,?,?,?,?,?)')->execute([$d['title'],$d['author'],$d['category'],(int)$d['year'],(int)$d['quantity'],(int)$d['quantity'],$d['description']??'']);json_out(['message'=>'Đã thêm sách','id'=>db()->lastInsertId()],201); }
  if($m==='PUT'&&$id){need($d,['title','author','category','year','quantity']);$old=db()->prepare('SELECT * FROM books WHERE id=?');$old->execute([$id]);$b=$old->fetch();if(!$b)json_out(['message'=>'Không tìm thấy sách'],404);$borrowed=(int)$b['quantity']-(int)$b['available'];if((int)$d['quantity']<$borrowed)json_out(['message'=>'Số lượng mới không được thấp hơn số bản đang được mượn'],409);$avail=(int)$d['quantity']-$borrowed;db()->prepare('UPDATE books SET title=?,author=?,category=?,year=?,quantity=?,available=?,description=? WHERE id=?')->execute([$d['title'],$d['author'],$d['category'],(int)$d['year'],(int)$d['quantity'],$avail,$d['description']??'',$id]);json_out(['message'=>'Đã cập nhật sách']); }
  if($m==='DELETE'&&$id){$s=db()->prepare('SELECT COUNT(*) FROM loans WHERE book_id=?');$s->execute([$id]);if($s->fetchColumn()>0)json_out(['message'=>'Không thể xóa sách đã có lịch sử mượn; hãy giữ lại để bảo toàn báo cáo'],409);$deleted=db()->prepare('DELETE FROM books WHERE id=?');$deleted->execute([$id]);if($deleted->rowCount()===0)json_out(['message'=>'Không tìm thấy sách'],404);json_out(['message'=>'Đã xóa sách']);}
 }
 if($r==='readers'){
   $u=current_user(); if($u['role']==='reader'){ if(!$u['reader_id'])json_out([]);$s=db()->prepare('SELECT * FROM readers WHERE id=?');$s->execute([$u['reader_id']]);json_out([$s->fetch()]); }
   if($m==='GET'){ $q=trim($_GET['q']??'');$st=$_GET['status']??'';$sql='SELECT * FROM readers WHERE 1';$a=[];if($q!==''){$sql.=' AND (name LIKE ? OR code LIKE ?)';$v="%$q%";$a=[$v,$v];}if($st!==''){$sql.=' AND status=?';$a[]=$st;}$s=db()->prepare($sql.' ORDER BY id DESC');$s->execute($a);json_out($s->fetchAll()); }
  require_role('librarian');$d=body();if($m==='POST'){need($d,['name','code','type']);db()->prepare("INSERT INTO readers(name,code,type,joined,borrowed,status) VALUES(?,?,?,CURDATE(),0,'active')")->execute([$d['name'],$d['code'],$d['type']]);json_out(['message'=>'Đã thêm độc giả'],201);}if($m==='PUT'&&$id){need($d,['name','code','type','status']);db()->prepare('UPDATE readers SET name=?,code=?,type=?,status=? WHERE id=?')->execute([$d['name'],$d['code'],$d['type'],$d['status'],$id]);json_out(['message'=>'Đã cập nhật độc giả']);}if($m==='DELETE'&&$id){$s=db()->prepare('SELECT COUNT(*) FROM loans WHERE reader_id=?');$s->execute([$id]);if($s->fetchColumn()>0)json_out(['message'=>'Không thể xóa độc giả đã có lịch sử mượn; hãy giữ lại để bảo toàn báo cáo'],409);$deleted=db()->prepare('DELETE FROM readers WHERE id=?');$deleted->execute([$id]);if($deleted->rowCount()===0)json_out(['message'=>'Không tìm thấy độc giả'],404);json_out(['message'=>'Đã xóa độc giả']);}
 }
 if($r==='loans'){
   $u=current_user(); if($m==='GET'){if($u['role']==='reader'){$s=db()->prepare('SELECT l.id,r.name reader,b.title book,l.borrowed,l.due,l.status FROM loans l JOIN readers r ON r.id=l.reader_id JOIN books b ON b.id=l.book_id WHERE l.reader_id=? ORDER BY l.id DESC');$s->execute([$u['reader_id']]);}else{$s=db()->query('SELECT l.id,r.name reader,b.title book,l.borrowed,l.due,l.status FROM loans l JOIN readers r ON r.id=l.reader_id JOIN books b ON b.id=l.book_id ORDER BY l.id DESC');}json_out($s->fetchAll());}
   require_role('librarian');$d=body();if($m==='POST'){need($d,['reader_id','book_id','borrowed','due']);db()->beginTransaction();$s=db()->prepare('SELECT available FROM books WHERE id=? FOR UPDATE');$s->execute([(int)$d['book_id']]);$av=$s->fetchColumn();if($av===false||$av<1){db()->rollBack();json_out(['message'=>'Sách hiện không còn bản có thể mượn'],409);}db()->prepare("INSERT INTO loans(reader_id,book_id,borrowed,due,status) VALUES(?,?,?,?,'open')")->execute([(int)$d['reader_id'],(int)$d['book_id'],$d['borrowed'],$d['due']]);db()->prepare('UPDATE books SET available=available-1 WHERE id=?')->execute([(int)$d['book_id']]);db()->prepare('UPDATE readers SET borrowed=borrowed+1 WHERE id=?')->execute([(int)$d['reader_id']]);db()->commit();json_out(['message'=>'Đã lập phiếu mượn'],201);}if($m==='PUT'&&$id&&($p[2]??'')==='return'){db()->beginTransaction();$s=db()->prepare('SELECT * FROM loans WHERE id=? FOR UPDATE');$s->execute([$id]);$l=$s->fetch();if(!$l||$l['status']==='returned'){db()->rollBack();json_out(['message'=>'Phiếu mượn không hợp lệ'],409);}db()->prepare("UPDATE loans SET status='returned',returned_at=CURDATE() WHERE id=?")->execute([$id]);db()->prepare('UPDATE books SET available=LEAST(quantity,available+1) WHERE id=?')->execute([$l['book_id']]);db()->prepare('UPDATE readers SET borrowed=GREATEST(0,borrowed-1) WHERE id=?')->execute([$l['reader_id']]);db()->commit();json_out(['message'=>'Đã ghi nhận trả sách']);}
 }
 if($r==='reservations'){
  $u=current_user();if($m==='GET'){if($u['role']==='reader'){$s=db()->prepare('SELECT x.id,r.name reader,b.title book,x.request_date date,x.position,x.status FROM reservations x JOIN readers r ON r.id=x.reader_id JOIN books b ON b.id=x.book_id WHERE x.reader_id=? ORDER BY x.id DESC');$s->execute([$u['reader_id']]);}else{$s=db()->query('SELECT x.id,r.name reader,b.title book,x.request_date date,x.position,x.status FROM reservations x JOIN readers r ON r.id=x.reader_id JOIN books b ON b.id=x.book_id ORDER BY x.id DESC');}json_out($s->fetchAll());}
  $d=body();if($m==='POST'){if($u['role']==='reader')$d['reader_id']=$u['reader_id'];need($d,['reader_id','book_id']);$duplicate=db()->prepare("SELECT COUNT(*) FROM reservations WHERE reader_id=? AND book_id=? AND status='pending'");$duplicate->execute([(int)$d['reader_id'],(int)$d['book_id']]);if($duplicate->fetchColumn()>0)json_out(['message'=>'Bạn đã có một yêu cầu đặt trước đang chờ cho sách này'],409);$s=db()->prepare("SELECT COUNT(*)+1 FROM reservations WHERE book_id=? AND status='pending'");$s->execute([(int)$d['book_id']]);$pos=(int)$s->fetchColumn();db()->prepare("INSERT INTO reservations(reader_id,book_id,request_date,position,status) VALUES(?,?,CURDATE(),?,'pending')")->execute([(int)$d['reader_id'],(int)$d['book_id'],$pos]);json_out(['message'=>'Đã tạo đặt trước'],201);}if($m==='DELETE'&&$id){$s=db()->prepare('SELECT reader_id FROM reservations WHERE id=?');$s->execute([$id]);$rid=$s->fetchColumn();if(!$rid)json_out(['message'=>'Không tìm thấy yêu cầu'],404);if($u['role']==='reader'&&(int)$rid!==(int)$u['reader_id'])json_out(['message'=>'Không có quyền'],403);db()->prepare("UPDATE reservations SET status='cancelled' WHERE id=?")->execute([$id]);json_out(['message'=>'Đã hủy đặt trước']);}
 }
 if($r==='ai'&&$m==='POST'){
   $u=current_user();$d=body();need($d,['prompt']);
   $result=ai_answer((string)$d['prompt'],$u);
   $response=json_encode($result,JSON_UNESCAPED_UNICODE);
   db()->prepare('INSERT INTO ai_logs(user_id,prompt,response) VALUES(?,?,?)')->execute([$u['id'],trim((string)$d['prompt']),$response]);
  $note = $result['warning'] ?? 'Kết quả được tạo từ dữ liệu thư viện đã lọc theo quyền truy cập.';
  json_out(['answer'=>$result['answer'],'sources'=>$result['sources'],'mode'=>$result['mode'],'note'=>$note]);
 }
 json_out(['message'=>'API không tồn tại'],404);
} catch(PDOException $e){ if(db()->inTransaction())db()->rollBack(); json_out(['message'=>'Lỗi truy vấn cơ sở dữ liệu. Ứng dụng vẫn hoạt động an toàn.'],500); } catch(Throwable $e){ $status=(int)$e->getCode(); if($status<400||$status>599)$status=500; json_out(['message'=>$e->getMessage()?:'Đã xảy ra lỗi không mong muốn.'],$status); }
