USE library_ai;
SET NAMES utf8mb4;

UPDATE books SET title='Nhà giả kim', author='Paulo Coelho', category='Văn học' WHERE id=1;
UPDATE books SET title='Clean Code', author='Robert C. Martin', category='Công nghệ' WHERE id=2;
UPDATE books SET title='Design of Everyday Things', author='Don Norman', category='Thiết kế' WHERE id=3;
UPDATE books SET title='Sapiens', author='Yuval Noah Harari', category='Lịch sử' WHERE id=4;
UPDATE books SET title='Tư duy nhanh và chậm', author='Daniel Kahneman', category='Kỹ năng' WHERE id=5;
UPDATE books SET title='Đắc nhân tâm', author='Dale Carnegie', category='Kỹ năng' WHERE id=6;
UPDATE books SET title='Tuổi trẻ đáng giá bao nhiêu', author='Rosie Nguyễn', category='Kỹ năng' WHERE id=7;
UPDATE books SET title='Atomic Habits', author='James Clear', category='Kỹ năng' WHERE id=8;
UPDATE books SET title='Thinking, Fast and Slow', author='Daniel Kahneman', category='Tâm lý' WHERE id=9;
UPDATE books SET title='Kẻ trộm sách', author='Markus Zusak', category='Văn học' WHERE id=10;
UPDATE books SET title='Bắt trẻ đồng xanh', author='J. D. Salinger', category='Văn học' WHERE id=11;
UPDATE books SET title='Kiêu hãnh và định kiến', author='Jane Austen', category='Văn học' WHERE id=12;
UPDATE books SET title='Ông già và biển cả', author='Ernest Hemingway', category='Văn học' WHERE id=13;
UPDATE books SET title='Bố già', author='Mario Puzo', category='Văn học' WHERE id=14;
UPDATE books SET title='The Pragmatic Programmer', author='Andrew Hunt, David Thomas', category='Công nghệ' WHERE id=15;
UPDATE books SET title='Refactoring', author='Martin Fowler', category='Công nghệ' WHERE id=16;
UPDATE books SET title='You Don''t Know JS Yet', author='Kyle Simpson', category='Công nghệ' WHERE id=17;
UPDATE books SET title='The Design of Everyday Things', author='Don Norman', category='Thiết kế' WHERE id=18;
UPDATE books SET title='Sapiens: Lược sử loài người', author='Yuval Noah Harari', category='Lịch sử' WHERE id=19;
UPDATE books SET title='21 bài học cho thế kỷ 21', author='Yuval Noah Harari', category='Lịch sử' WHERE id=20;
UPDATE books SET title='Nhà lãnh đạo không chức danh', author='Robin Sharma', category='Kinh doanh' WHERE id=21;
UPDATE books SET title='Từ tốt đến vĩ đại', author='Jim Collins', category='Kinh doanh' WHERE id=22;
UPDATE books SET title='Zero to One', author='Peter Thiel', category='Kinh doanh' WHERE id=23;
UPDATE books SET title='Một đời đáng giá bao nhiêu', author='Phan Văn Trường', category='Phát triển bản thân' WHERE id=24;
UPDATE books SET title='Muôn kiếp nhân sinh', author='Nguyễn Phong', category='Tâm linh' WHERE id=25;

UPDATE books SET description='Hành trình theo đuổi kho báu và lắng nghe tiếng gọi nội tâm.' WHERE id=1;
UPDATE books SET description='Những nguyên tắc viết mã nguồn sạch và dễ bảo trì.' WHERE id=2;
UPDATE books SET description='Tư duy thiết kế lấy con người làm trung tâm.' WHERE id=3;
UPDATE books SET description='Lược sử loài người từ thời tiền sử đến hiện đại.' WHERE id=4;
UPDATE books SET description='Hai hệ thống tư duy và những thiên kiến trong quyết định.' WHERE id=5;
UPDATE books SET description='Những bài học kinh điển về nghệ thuật ứng xử và phát triển bản thân.' WHERE id=6;
UPDATE books SET description='Những suy ngẫm thực tế về tuổi trẻ, lựa chọn và giá trị sống.' WHERE id=7;
UPDATE books SET description='Phương pháp xây dựng thói quen tốt và thay đổi bền vững.' WHERE id=8;
UPDATE books SET description='Phân tích hai hệ thống tư duy và các sai lầm trong phán đoán.' WHERE id=9;
UPDATE books SET description='Câu chuyện về tình yêu sách và nghị lực sống trong thời chiến.' WHERE id=10;
UPDATE books SET description='Tiểu thuyết về tuổi trưởng thành và sự cô đơn của một thiếu niên.' WHERE id=11;
UPDATE books SET description='Câu chuyện kinh điển về tình yêu, gia đình và định kiến xã hội.' WHERE id=12;
UPDATE books SET description='Cuộc phiêu lưu của một ông lão đánh cá giữa biển cả.' WHERE id=13;
UPDATE books SET description='Tiểu thuyết nổi tiếng về gia đình, quyền lực và lòng trung thành.' WHERE id=14;
UPDATE books SET description='Các nguyên tắc thực tế để xây dựng phần mềm tốt và dễ bảo trì.' WHERE id=15;
UPDATE books SET description='Phương pháp cải thiện thiết kế mã nguồn mà không thay đổi hành vi.' WHERE id=16;
UPDATE books SET description='Hướng dẫn thực hành JavaScript qua các ví dụ gần gũi.' WHERE id=17;
UPDATE books SET description='Những nguyên tắc thiết kế sản phẩm dễ hiểu và dễ sử dụng.' WHERE id=18;
UPDATE books SET description='Câu chuyện lớn về lịch sử và sự phát triển của loài người.' WHERE id=19;
UPDATE books SET description='Hai mươi mốt bài học về thế giới hiện đại và tương lai.' WHERE id=20;
UPDATE books SET description='Những nguyên tắc lãnh đạo và tạo ảnh hưởng không phụ thuộc chức danh.' WHERE id=21;
UPDATE books SET description='Các yếu tố giúp một tổ chức chuyển từ tốt đến vĩ đại.' WHERE id=22;
UPDATE books SET description='Tư duy khởi nghiệp và cách tạo ra giá trị khác biệt.' WHERE id=23;
UPDATE books SET description='Những suy ngẫm về hành trình sống và giá trị của mỗi con người.' WHERE id=24;
UPDATE books SET description='Những chiêm nghiệm về luật nhân quả và hành trình làm người.' WHERE id=25;